services:
  actualbudget:
    image: actualbudget/actual-server:latest
    container_name: actualbudget
    restart: unless-stopped
    volumes:
      - /volume1/docker-data/actualbudget/data:/data
    networks:
      - caddy

networks:
  caddy:
    external: true
    name: caddy
